# Generated by Django 5.1.4 on 2025-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'United States'), ('BR', 'Brazil'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('MX', 'Mexico'), ('PT', 'Portugal'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('AR', 'Argentina'), ('PE', 'Peru'), ('CL', 'Chile')], max_length=100, null=True)),
            ],
        ),
    ]
